### ISSUE TITLE
Key Identification during MDT deployment

### ISSUE THREAD

**Issue by fthobe** [MattiasC85/Scripts#9]
Hey Mattias,

Thank you for your hard work, your blog and GitHub repo was a significant source of information.

We are refurbishing computers to give away to schools.

The devices we receive have various different OEM licenses installed and it seems like former users can't help themselves and peel off the license stickers.

We have made great steps forward regarding identifying the license post installation with powershell running Get-WmiObject 'SoftwareLicensingService' as querying OA3xOriginalProductKeyDescription returns the effective version. We do significantly struggle determining that during deploy though and setting a variable to determine the right OS to install.

Any ideas how that would look like? I saw your key identification app, did you ever implement it with MDT and managed to store the key description in an MDT task sequence variable?

Fab

**Comment by MattiasC85** [comment]
Hi Fab!

Dang, haven't used MDT in ages and when I made that OEM tool "OA3xOriginalProductKeyDescription" wasn't even available in WinPE.

Anyway, ofc I can try to help ya.
The task sequence, is that started from within Windows or do you PXE boot?

If you start it from Windows you should be able to set a variable, running a Powershell script, as a step in the sequence. If you PXE boot you must first confirm that the WMI command works in WinPE. It should work but just to confirm.

So what you need help with is creating a script that sets a TS variable with the value of "OA3xOriginalProductKeyDescription", and then use that variable as an option to some steps later in the TS, is that correct?

Let me know and I can post a script doing just that if that is what you need.

Cheers and thank you for the kind words!

**Comment by MattiasC85** [comment]
Personally I wouldn't trust "OA3xOriginalProductKeyDescription" since that is blank on my computer and it can have different values both when it comes to manufacturers and computer models and perhaps even bios versions as well(?)

But this script should do it if you concluded that the property is set and has the expected values on all of your machines...

#Defines SCCM TS Variable Environment, only exist when running a TS
$tsenv = New-Object -COMObject Microsoft.SMS.TSEnvironment

#Reads variable from Task Sequence
$v = $tsenv.Value("OA3xOrigPKDesc")

#Get the value
$KeyDesc = (Get-WmiObject softwarelicensingservice).OA3xOriginalProductKeyDescription

#Sets variable in TSEnv
$tsenv.Value("OA3xOrigPKDesc") = $KeyDesc

Then set the option on the step to only run, or not to run, when it has a specific value.

![image](https://github.com/user-attachments/assets/8c3ecbe2-b124-446d-85f9-4c3fe46ddb9e)
